export const onboarding = new Map()
export const upgradeFlow = new Map()
export const billingFlow = new Map()
export const onboardingReminders = new Map()
export const upgradeReminders = new Map()
export const billingReminders = new Map()
